### ISSUE TITLE
linux-aarch64/linux-aarch32 build

### ISSUE THREAD

**Issue by analog-cbarber** [conda-forge/cloudpathlib-feedstock#29]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Can you add a linux-aarch64 build? I would like to be able to install this in a Rasberry Pi from conda.

Even better would be to just convert this to a noarch python package
(just remove preprocessing selector for importlib_metadata, it doesn't
cost that much to just always include it until you drop support for python 3.7)

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by jayqi** [comment]
Hi @analog-cbarber. I've converted this recipe to a `noarch: python` package per your suggestion (#39, #40) . This should be available now for v0.13.0. If you need an earlier version, let me know.

```
❯ mamba search cloudpathlib* -c conda-forge/noarch --override-channels

Loading channels: done
# Name                       Version           Build  Channel
cloudpathlib                  0.13.0    pyh1a96a4e_1  conda-forge
cloudpathlib                  0.13.0    pyh44b312d_1  conda-forge
cloudpathlib                  0.13.0    pyh6c4a22f_1  conda-forge
cloudpathlib                  0.13.0    pyhca7485f_1  conda-forge
cloudpathlib                  0.13.0    pyhd8ed1ab_1  conda-forge
cloudpathlib                  0.13.0    pyhd8ed1ab_2  conda-forge
cloudpathlib-all              0.13.0    pyhd8ed1ab_1  conda-forge
cloudpathlib-all              0.13.0    pyhd8ed1ab_2  conda-forge
cloudpathlib-azure            0.13.0    pyhd8ed1ab_1  conda-forge
cloudpathlib-azure            0.13.0    pyhd8ed1ab_2  conda-forge
cloudpathlib-gs               0.13.0    pyhd8ed1ab_1  conda-forge
cloudpathlib-gs               0.13.0    pyhd8ed1ab_2  conda-forge
cloudpathlib-s3               0.13.0    pyhd8ed1ab_1  conda-forge
cloudpathlib-s3               0.13.0    pyhd8ed1ab_2  conda-forge
```

I think a version specification like this should get you what you need if you want to force a noarch version. 

```bash
mamba install "cloudpathlib-s3=*=pyh*" --dry-run
```
