### ISSUE TITLE
Missing 0.10.0 version

### ISSUE THREAD

**Issue by remi-braun** [conda-forge/cloudpathlib-feedstock#32]
Only cloudpathlib 0.9.0 is available on conda-forge. Would it be possible to have 0.10.0 too ?

**Comment by jayqi** [comment]
v0.10.0 should [be available](https://anaconda.org/conda-forge/cloudpathlib/files?version=0.10.0) with the merging of #31. Sorry that I forgot to follow up on commenting and closing this issue.
